### ISSUE TITLE
Cannot resolve package

### ISSUE THREAD

**Issue by wasabii** [ikvmnet/ikvm-maven#39]
@wasabii I'm sorry I am disturbing you

After adding this:
```
  <ItemGroup>
        <PackageReference Include="IKVM" Version="8.7.1-pre.3" />
        <PackageReference Include="IKVM.Maven.Sdk" Version="1.6.1" />
    </ItemGroup>

    <ItemGroup>
        <MavenReference Include="org.apache.calcite:calcite-core" Version="1.34.0" />
        <MavenReference Include="org.apache.calcite.avatica:avatica-server" Version="1.23.0" />
        <MavenReference Include="org.apache.calcite:calcite-csv" Version="1.34.0" /> <--- this is the refence that breaks
    </ItemGroup>
```
Error:
`0>IKVM.Maven.Sdk.targets(96,9): Error  : DependencyResolutionException: Could not find artifact javax.jms:jms:jar:1.1 in central (https://repo1.maven.org/maven2/), try downloading from http://java.sun.com/products/jms/docs.html
   at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(RepositorySystemSession session, DependencyRequest request)
   at IKVM.Maven.Sdk.Tasks.MavenReferenceItemResolve.ResolveCompileDependencyGraph(IkvmMavenEnvironment maven, RepositorySystemSession session, IList`1 repositories, IList`1 items) in C:\w\ikvm-maven\src\IKVM.Maven.Sdk.Tasks\MavenReferenceItemResolve.cs:line 254
   at IKVM.Maven.Sdk.Tasks.MavenReferenceItemResolve.ResolveReferences(IList`1 repositories, IList`1 items) in C:\w\ikvm-maven\src\IKVM.Maven.Sdk.Tasks\MavenReferenceItemResolve.cs:line 193
   at IKVM.Maven.Sdk.Tasks.MavenReferenceItemResolve.Execute() in C:\w\ikvm-maven\src\IKVM.Maven.Sdk.Tasks\MavenReferenceItemResolve.cs:line 151
ArtifactResolutionException: Could not find artifact javax.jms:jms:jar:1.1 in central (https://repo1.maven.org/maven2/), try downloading from http://java.sun.com/products/jms/docs.html
   at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(RepositorySystemSession session, Collection requests)
   at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(RepositorySystemSession session, DependencyRequest request)
ArtifactNotFoundException: Could not find artifact javax.jms:jms:jar:1.1 in central (https://repo1.maven.org/maven2/), try downloading from http://java.sun.com/products/jms/docs.html
`
As a result all dependencies are being deleted ( aka not created )

_Originally posted by @HackPoint in https://github.com/ikvmnet/ikvm/issues/438#issuecomment-1789581746_

**Comment by wasabii** [comment]
So as far as I can tell, this is ... normal.

https://stackoverflow.com/questions/4908651/the-following-artifacts-could-not-be-resolved-javax-jmsjmsjar1-1

The deal seems to be that the JMS dependency has no JAR file in Maven Central. And the JAR file only exists in the JBoss repository. So the JBoss repository needs to be added.

**Comment by jeremyosterhoudt** [comment]
Is there a way to add a custom repository using the `IKVM.Maven.Sdk` package or would we need to download the JMS.jar independently and include it with the `IkvmReference` property in the project file?

**Comment by wasabii** [comment]
```
<PropertyGroup>
<MavenAdditionalRepositories>$(MavenAdditionalRepositories);myrepo=http://myrepo.com/whatever</MavenAdditionalRepositories>
</PropertyGroup>

**Comment by HackPoint** [comment]
@wasabii can you please explain why the assemblies aren't being generated through the IKVM transpiler? Like I shown you in issue 41

**Comment by wasabii** [comment]
The code you submitted to demonstrate issue #41 resulted, for me, in the error shown here on issue #39.

**Comment by HackPoint** [comment]
Still having an error with this configuration:
```
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net7.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <MavenAdditionalRepositories>$(MavenAdditionalRepositories);myrepo=https://repository.jboss.org/nexus/content/groups/public</MavenAdditionalRepositories>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="IKVM" Version="8.7.1" />
        <PackageReference Include="IKVM.Maven.Sdk" Version="1.6.0" />
    </ItemGroup>
    <ItemGroup>
        <MavenReference Include="javax.jms:jms" Version="1.1" />
        <MavenReference Include="org.apache.calcite:calcite-core" Version="1.34.0" />
        <MavenReference Include="org.apache.calcite:calcite-server" Version="1.34.0" />
        <MavenReference Include="org.apache.calcite:calcite-csv" Version="1.34.0" />
        <MavenReference Include="org.apache.calcite:calcite-elasticsearch" Version="1.34.0" />
        <MavenReference Include="org.apache.calcite.avatica:avatica-server" Version="1.23.0" />
    </ItemGroup>
</Project>
```


```
Error  : DependencyResolutionException: The following artifacts could not be resolved: javax.jms:jms:jar:1.1, javax.jms:jms:jar:1.1: Could not find artifact javax.jms:jms:jar:1.1 in central (https://repo1.maven.org/maven2/), try downloading from http://java.sun.com/products/jms/docs.html
   at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(RepositorySystemSession session, DependencyRequest request)
   at IKVM.Maven.Sdk.Tasks.MavenReferenceItemResolve.ResolveCompileDependencyGraph(IkvmMavenEnvironment maven, RepositorySystemSession session, IList`1 repositories, IList`1 items) in C:\w\ikvm-maven\src\IKVM.Maven.Sdk.Tasks\MavenReferenceItemResolve.cs:line 254
   at IKVM.Maven.Sdk.Tasks.MavenReferenceItemResolve.ResolveReferences(IList`1 repositories, IList`1 items) in C:\w\ikvm-maven\src\IKVM.Maven.Sdk.Tasks\MavenReferenceItemResolve.cs:line 193
   at IKVM.Maven.Sdk.Tasks.MavenReferenceItemResolve.Execute() in C:\w\ikvm-maven\src\IKVM.Maven.Sdk.Tasks\MavenReferenceItemResolve.cs:line 151
ArtifactResolutionException: The following artifacts could not be resolved: javax.jms:jms:jar:1.1, javax.jms:jms:jar:1.1: Could not find artifact javax.jms:jms:jar:1.1 in central (https://repo1.maven.org/maven2/), try downloading from http://java.sun.com/products/jms/docs.html
   at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(RepositorySystemSession session, Collection requests)
   at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(RepositorySystemSession session, DependencyRequest request)
ArtifactNotFoundException: Could not find artifact javax.jms:jms:jar:1.1 in central (https://repo1.maven.org/maven2/), try downloading from http://java.sun.com/products/jms/docs.html
```

**Comment by wasabii** [comment]
The project file you just posted builds fine for me with no error. The error you posted indicates that the repository has not been added. So I'm not sure whether you need to rebuild or what. But, the configuration you posted works.

**Comment by wasabii** [comment]
No response, issue stale. Assuming fixed. Reopen if not.
