### ISSUE TITLE
Stanford CoreNLP using MavenReference (.NET 6, IKVM 8.7.3, IKVM.Maven.Sdk 1.6.2)

### ISSUE THREAD

**Issue by sergey-tihon** [ikvmnet/ikvm-maven#46]
Hi, I just tried to migrate `CoreNLP` tests to `MavenReference` and all tests failed in runtime

```
     at java.lang.ThreadLocal.nextHashCode()
     at java.lang.ThreadLocal..ctor()
     at ikvm.internal.IntrinsicThreadLocal..ctor()
     at java.nio.charset.Charset.__<tls>_0..ctor()
     at java.nio.charset.Charset..cctor()
```

here is runnable PR - https://github.com/sergey-tihon/Stanford.NLP.NET/pull/130 and errors from the CI https://github.com/sergey-tihon/Stanford.NLP.NET/actions/runs/7160234064/job/19494381165?pr=130

Full stack trace from one tests
```
  Error Message:
   System.TypeInitializationException : The type initializer for 'edu.stanford.nlp.pipeline.Annotation' threw an exception.
---- System.TypeInitializationException : The type initializer for 'edu.stanford.nlp.util.ArrayCoreMap' threw an exception.
-------- System.TypeInitializationException : The type initializer for 'java.lang.ThreadLocal' threw an exception.
------------ System.TypeInitializationException : The type initializer for 'java.util.concurrent.atomic.AtomicInteger' threw an exception.
---------------- System.TypeInitializationException : The type initializer for 'java.lang.Object' threw an exception.
-------------------- System.TypeInitializationException : The type initializer for 'java.nio.charset.Charset' threw an exception.
------------------------ System.NullReferenceException : Object reference not set to an instance of an object.
  Stack Trace:
     at edu.stanford.nlp.pipeline.Annotation..ctor(String text)
   at Stanford.NLP.CoreNLP.Tests.Samples.CorefTests.CorefTest() in /Users/sergey_tihon/git/Stanford.NLP.NET/tests/Stanford.NLP.CoreNLP.Tests/Samples/CorefTests.cs:line 29
----- Inner Stack Trace -----
   at edu.stanford.nlp.util.ArrayCoreMap.__<clinit>()
   at edu.stanford.nlp.pipeline.Annotation..cctor()
----- Inner Stack Trace -----
   at java.lang.ThreadLocal.withInitial(Supplier supplier)
   at edu.stanford.nlp.util.ArrayCoreMap..cctor()
----- Inner Stack Trace -----
   at java.util.concurrent.atomic.AtomicInteger..ctor()
   at java.lang.ThreadLocal..cctor()
----- Inner Stack Trace -----
   at java.lang.Object..ctor()
   at ikvm.internal.CallerID..ctor()
   at ikvm.internal.CallerID.2..ctor(RuntimeTypeHandle val$typeHandle)
   at ikvm.internal.CallerID.create(RuntimeTypeHandle typeHandle)
   at java.util.concurrent.atomic.AtomicInteger.__<GetCallerID>()
   at java.util.concurrent.atomic.AtomicInteger..cctor()
----- Inner Stack Trace -----
   at java.nio.charset.Charset.defaultCharset()
   at sun.nio.cs.StreamEncoder.forOutputStreamWriter(OutputStream out, Object lock, String charsetName)
   at java.io.OutputStreamWriter..ctor(OutputStream out)
   at java.io.PrintStream..ctor(Boolean autoFlush, OutputStream out)
   at java.io.PrintStream..ctor(OutputStream out, Boolean autoFlush)
   at java.lang.System.newPrintStream(FileOutputStream fos, String enc)
   at java.lang.System.initializeSystemClass()
   at __<MethodAccessor>__System__initializeSystemClass()
   at IKVM.Runtime.Accessors.Java.Lang.SystemAccessor.InvokeInitializeSystemClass()
   at IKVM.Runtime.JVM.EnsureInitialized()
   at java.lang.Object..cctor()
----- Inner Stack Trace -----
   at java.lang.ThreadLocal.nextHashCode()
   at java.lang.ThreadLocal..ctor()
   at ikvm.internal.IntrinsicThreadLocal..ctor()
   at java.nio.charset.Charset.__<tls>_0..ctor()
   at java.nio.charset.Charset..cctor()
```

Any idea why it happens?

**Comment by wasabii** [comment]
Can you stick new java.lang.Object() as the first thing in the first method you call?

**Comment by sergey-tihon** [comment]
You are right, this works. https://github.com/sergey-tihon/Stanford.NLP.NET/pull/130/commits/ec1eb19e0ca98bdb4bb652edee6ca2197e723201

What is it?

**Comment by wasabii** [comment]
https://github.com/ikvmnet/ikvm/issues/423

Haven't got around to figuring it out.

**Comment by sergey-tihon** [comment]
Interesting that I did not face this issue before when building jar files by myself...

May it be related to newer versions of IKVM or the way MavenReference works?

**Comment by sergey-tihon** [comment]
Closed as duplicate https://github.com/ikvmnet/ikvm/issues/423
